/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\tzqApp\\code\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-7c4d4580",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7c4d4580").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-e42b2414",
    path: "/chapter1/01_%E5%88%9D%E8%AF%86TS.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e42b2414").then(next)
    },
  },
  {
    path: "/chapter1/01_初识TS.html",
    redirect: "/chapter1/01_%E5%88%9D%E8%AF%86TS.html"
  },
  {
    path: "/chapter1/01_初识TS.html",
    redirect: "/chapter1/01_%E5%88%9D%E8%AF%86TS.html"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]