/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "大王",
  "description": "大王测试",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/logo.png"
      }
    ]
  ],
  "pages": [
    {
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-7c4d4580",
      "path": "/"
    },
    {
      "title": "01_初识TS",
      "frontmatter": {},
      "regularPath": "/chapter1/01_%E5%88%9D%E8%AF%86TS.html",
      "relativePath": "chapter1/01_初识TS.md",
      "key": "v-e42b2414",
      "path": "/chapter1/01_%E5%88%9D%E8%AF%86TS.html",
      "headers": [
        {
          "level": 2,
          "title": "01_初识TS",
          "slug": "_01-初识ts"
        },
        {
          "level": 3,
          "title": "你好啊",
          "slug": "你好啊"
        }
      ]
    }
  ],
  "themeConfig": {
    "search": true,
    "searchMaxSuggestions": 10,
    "logo": "/erya.jpg",
    "nav": [
      {
        "text": "Home",
        "link": "/"
      },
      {
        "text": "百度",
        "link": "https:www.baidu.com"
      },
      {
        "text": "语言",
        "ariaLabel": "Language Menu",
        "items": [
          {
            "text": "中文",
            "link": "/language/chinese/"
          },
          {
            "text": "english",
            "link": "/language/english"
          }
        ]
      }
    ],
    "sidebar": [
      {
        "title": "初识 TypeScript",
        "collapsable": false,
        "children": [
          [
            "chapter1/01_初识TS",
            "你好Ts"
          ]
        ]
      }
    ],
    "lastUpdated": "Last Updated"
  }
}