/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Adroi媒体API 接口文档",
  "description": "Adroi",
  "base": "/code/",
  "headTags": [],
  "pages": [
    {
      "title": "hello",
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-98dc3666",
      "path": "/",
      "headers": [
        {
          "level": 2,
          "title": "hello",
          "slug": "hello"
        }
      ]
    },
    {
      "title": "01_初识TS",
      "frontmatter": {},
      "regularPath": "/chapter1/01_%E5%88%9D%E8%AF%86TS.html",
      "relativePath": "chapter1/01_初识TS.md",
      "key": "v-f5aba26e",
      "path": "/chapter1/01_%E5%88%9D%E8%AF%86TS.html",
      "headers": [
        {
          "level": 2,
          "title": "01_初识TS",
          "slug": "_01-初识ts"
        }
      ]
    }
  ],
  "themeConfig": {
    "logo": "/erya.jpg",
    "nav": [
      {
        "text": "接口定义",
        "link": "/apiword"
      },
      {
        "text": "接口字段定义",
        "link": "/api"
      },
      {
        "text": "附录：错误码",
        "link": "/error"
      }
    ],
    "sidebar": [
      {
        "title": "初识 TypeScript",
        "collapsable": false,
        "children": [
          [
            "chapter1/01_初识TS",
            "你好Ts"
          ]
        ]
      }
    ],
    "lastUpdated": "Last Updated",
    "sidebarDepth": 2
  }
}